version: '2'
services:
  # registry-web管理
  registry-web:
    image: hyper/docker-registry-web
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/docker/registry/conf/registry-web.yml:/conf/config.yml:ro
      - /data/docker/registry/cert/auth.key:/conf/auth.key
      - /data/docker/registry/data:/data
    depends_on:
      - registry
    restart: always
    container_name: registry-web
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
