version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    volumes:
      - data:/usr/share/elasticsearch/data
      - /data/docker/elk-7.4.2/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: 'always'
    container_name: elasticsearch
    networks:
      - custom_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    ports:
      - '5044:5044'
      - '5569:5569'
      - '9600:9600'
    environment:
      - 'LS_JAVA_OPTS=-Xms256m -Xmx256m'
    volumes:
      - /data/docker/elk-7.4.2/logstash/pipeline:/usr/share/logstash/pipeline
      - /data/docker/elk-7.4.2/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch
    restart: 'always'
    container_name: logstash
    networks:
      - custom_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
      - '5601:5601'
    volumes:
      - /data/docker/elk-7.4.2/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    restart: 'always'
    container_name: kibana
    networks:
      - custom_network

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /data/docker/elk-7.4.2/redis/data:/data
    restart: always
    container_name: redis
    networks:
      - custom_network

volumes:
  data:

networks:
  custom_network:
    external:
      name: elk
