version: '2'
services:
  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/docker/registry/auth:/auth
      - /data/docker/registry/repositories:/var/lib/registry
    environment:
      - 'REGISTRY_AUTH=htpasswd'
      - 'REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm'
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    restart: always
    container_name: registry
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
