version: '3'
services:
  # redis
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/docker/redis/data:/data
    restart: always
    container_name: redis
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
