version: "3"

services:
  flarum:
    image: mondedie/docker-flarum:0.1.0-beta.8.1-stable
    env_file:
      - /data/docker/flarum/flarum.env
    volumes:
      - /data/docker/flarum/assets:/flarum/app/public/assets
      - /data/docker/flarum/extensions:/flarum/app/extensions
      - /data/docker/flarum/nginx:/etc/nginx/conf.d
    depends_on:
      - mariadb
    ports:
    - "8080:80"
    restart: always
    container_name: flarum
    networks:
    - custom_network

networks:
  custom_network:
    external:
      name: local_network
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Wang4995
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=Wang4995
    volumes:
      - /data/docker/mysql/db:/var/lib/mysql