version: '2'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - '2181:2181'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    container_name: zookeeper
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
