version: '3'

services:
  php-web:
    build: .
    image: php-web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '8080:80'
    restart: always
    container_name: php-web
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
