version: '3'
services:
  # postgresql数据库
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    container_name: sonarqube-postgresql
    networks:
      - custom_network

  # sonarqube服务
  sonarqube:
    image: sonarqube
    ports:
      - '9000:9000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    restart: always
    container_name: sonarqube
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
