version: '3'

services:
  jenkins-blueocean:
    image: jenkinsci/blueocean
    ports:
      - '8082:8080'
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
      - /data/docker/jenkins-blueocean/jenkins_home:/var/jenkins_home
    restart: always
    container_name: jenkins-blueocean
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
