version: '3'

services:
  jenkins-blueocean:
    build: .
    image: jenkins/blueocean
    ports:
      - '8082:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/jenkins-blueocean/jenkins_home:/var/jenkins_home
    restart: always
    container_name: jenkins-blueocean
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
