version: '3'
services:
  postgis:
    image: mdillon/postgis:9.4
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/docker/postgis/data:/var/lib/postgresql/data
    restart: always
    container_name: postgis
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
