version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    container_name: elasticsearch
    networks:
      - custom_network

  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    ports:
      - 9100:9100
    container_name: elasticsearch-head
    networks:
      - custom_network

volumes:
  elasticsearch-data:

networks:
  custom_network:
    external:
      name: app
