version: '3'
services:
  # mysql服务
  mysql:
    image: docker.io/mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/docker/mysql-5.7/conf:/etc/mysql/conf.d
      - /data/docker/mysql-5.7/data:/var/lib/mysql
    restart: always
    container_name: mysql
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: app
